### ISSUE TITLE
release of zarith.js as separate opam package ?

### ISSUE THREAD

**Issue by abate** [cpitclaudel/fstar.js#2]
Hello,

Would you consider creating a separate ocaml package with only the zarith js bindings and
add it to the opam repository ?

I'm creating a library that uses hacl compiled to wasm and I also need zarith, it would be nice
to just depend on a zarith-js package for this component.

I can propose a MR or we can create contribute the packaging in a separate repository and then have fstar-js to depend on that package as well.

**Comment by hhugo** [comment]
Ideally, the js runtime should live in https://github.com/ocaml/Zarith with the right thingy in the meta so that things work out of the box when using dune.

Alternatively, I'm happy to have the runtime included in js_of_ocaml.

**Comment by cpitclaudel** [comment]
Hi all!  I don't have much time to dedicate to this, but you have my blessing to include this code where it'd be most convenient for it to reside.  I can relicense it as needed to make this easier.

**Comment by hhugo** [comment]
https://github.com/janestreet/zarith_stubs_js was just released and provides all zarith's primitives

**Comment by hhugo** [comment]
zarith_stubs_js was just released in opam https://github.com/ocaml/opam-repository/pull/15098

**Comment by cpitclaudel** [comment]
Nice, thanks for the update! :)
